### ISSUE TITLE
Push notifications on new blocks and transactions

### ISSUE THREAD

**Issue by ogminor** [ruby-wallet/ruby-wallet#2]
I don't want to have to short poll for changes, I should get push notifications. If we are going through the effort of abstracting the wallet, we might as well get some more use out of it.

**Comment by drunkonsound** [comment]
This would only be possible if we generated the config files for the coind clients. However you can achieve this through walletnotify or blocknotify, and I will provide scripts in the new version (you know this because you gave me the notify scripts).
